spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://taskDatabase:5432/task
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
secret:
  key: "gi5h4ni445985jv84b985b4h984bn98btn8b93v39rt3bt930vm30b4t3v3tiv38b"
auth.service.url: "http://auth:8080"
account.service.url: "http://account:8081"
logging:
  level:
    org.springframework.security: DEBUG