services:
  taskDatabase:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "task"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
  
  accountDatabase:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: "task"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - 6379:6379

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth:
    build: 
      dockerfile: ./AuthDockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
      - kafka

  account:
    build: 
      dockerfile: ./AccountDockerfile
    ports:
      - 8081:8081
    depends_on:
      - accountDatabase

  task:
    build: 
      dockerfile: ./TaskDockerfile
    ports:
      - 8082:8082
    depends_on:
      - taskDatabase

  # kafka-ui:
  #   image: provectuslabs/kafka-ui
  #   container_name: kafka-ui
  #   ports:
  #     - 8090:8080
  #   restart: always
  #   links:
  #     - kafka
  #     - zookeeper
  #   environment:
  #     - KAFKA_CLUSTERS_0_NAME=cluster
  #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
  #     - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181