version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: task
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres

  tasks:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db