spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5434/task
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
secret:
  key: "gi5h4ni445985jv84b985b4h984bn98btn8b93v39rt3bt930vm30b4t3v3tiv38b"
auth:
  service:
    url: "http://localhost:8080"

logging:
  level:
    org.springframework.security: DEBUG