secret:
  key: "gi5h4ni445985jv84b985b4h984bn98btn8b93v39rt3bt930vm30b4t3v3tiv38b"
  duration: 3600000
#account.service.url: "http://account:8081/accountApi"
account.service.url: "http://localhost:8081/accountApi"
spring:
  data:
    redis:
      port: 6379
#      host: redis
      host: localhost
  kafka:
#    bootstrap-servers: "kafka:29092"
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
